# Generated by Django 3.1.7 on 2021-04-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(
                default='/Users/truong/Edu/cs50w/tweeter/network/mediaavatar.jpg', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
