# Generated by Django 3.1.7 on 2021-04-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210414_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(
                default='/Users/truong/Edu/cs50w/tweeter/network/mediaavatar.jpg', upload_to='uploads/'),
        ),
    ]
