# Generated by Django 3.1.7 on 2021-04-14 13:58

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210414_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', upload_to=network.models.user_directory_path),
        ),
    ]
